/**
 * @file walker_state_machine.hpp
 * @author Grayson Gilbert (ggilbert@umd.edu)
 * @brief Finite State Machine implementation for controlling the walker robot
 * @version 0.1
 * @date 2025-11-21
 * 
 * @copyright Copyright (c) 2025
 * 
 */

// Copyright 2025 Grayson Gilbert
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


#ifndef MY_WEBOTS_TUTORIALS_WALKER_HPP_
#define MY_WEBOTS_TUTORIALS_WALKER_HPP_


#include <algorithm>
#include <memory>

#include "my_webots_tutorials/walker_state_interface.hpp"


class WalkerStateMachine {
    public:
        /**
        * @brief Construct a new WalkerStateMachine and set the initial state.
        * 
        */
        WalkerStateMachine(){

            current_state_ = std::make_unique<state_MoveForward>();
        }

        /**
         * @brief Delegates to the current state's movement logic.
         * 
         * @param left_sensor - Current reading from the left distance sensor.
         * @param right_sensor - Current reading from the right distance sensor.
         * @return std::unique_ptr<geometry_msgs::msg::Twist> - The movement command generated by the active state.
         */
        std::unique_ptr<geometry_msgs::msg::Twist> movement_state(double left_sensor, double right_sensor);

        /**
         * @brief Ask the current state whether a transition should occur.
         * 
         * @param left_sensor - Current reading from the left distance sensor.
         * @param right_sensor - Current reading from the right distance sensor.
         * @return std::unique_ptr<WalkerStateInterface> - Newly created next state, or nullptr if no transition should occur.
         */
        std::unique_ptr<WalkerStateInterface> transition_state(double left_sensor, double right_sensor);
        
        /**
         * @brief Get a human-readable name for the current state
         * 
         * @return const char* - string idenfitier for the state
         */
        const char* state_name() const { return current_state_ ? current_state_->state_name() : "(no state)"; }

    protected:

        // Forward Robot Movement State
        class state_MoveForward : public WalkerStateInterface
        {
            public: 

                virtual std::unique_ptr<geometry_msgs::msg::Twist> movement_state(double left_sensor, double right_sensor) override;


                virtual std::unique_ptr<WalkerStateInterface> transition_state(double left_sensor, double right_sensor) override;

                const char* state_name() const override { return "Forward State"; }
        };

        // Turning Robot Movement State
        class state_Turn : public WalkerStateInterface
        {
            public: 

                virtual std::unique_ptr<geometry_msgs::msg::Twist> movement_state(double left_sensor, double right_sensor) override;


                virtual std::unique_ptr<WalkerStateInterface> transition_state(double left_sensor, double right_sensor) override;

                const char* state_name() const override { return "Turn State"; }
        };

    private:
        std::unique_ptr<WalkerStateInterface> current_state_; // Pointer to the current robot state
};

#endif // MY_WEBOTS_TUTORIALS_WALKER_HPP_
